<?php declare(strict_types=1);

namespace Krasilnikovs\Opengraph\Property;

final readonly class DeterminerProperty extends AbstractProperty
{
    public static function getName(): string
    {
        return 'og:determiner';
    }

    public static function fromString(string $content): static
    {
        $determiner = Determiner::tryFrom($content) ?? Determiner::Empty;

        return parent::fromString($determiner->value); // TODO: Change the autogenerated stub
    }
}
